export const cabinetStatus = [
  {
    cabinetNumber: 1,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '함윤호',
    unavailableReason: '',
  },
  {
    cabinetNumber: 2,
    status: 'waiting',
    start: '',
    end: '',
    lender: '손기배',
    unavailableReason: '',
  },
  {
    cabinetNumber: 3,
    status: 'unavailable',
    start: '',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    cabinetNumber: 4,
    status: 'unavailable',
    start: '',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    cabinetNumber: 5,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '윤찬호',
    unavailableReason: '',
  },
  {
    cabinetNumber: 6,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '이지우',
    unavailableReason: '',
  },
  {
    cabinetNumber: 7,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '김진호',
    unavailableReason: '',
  },
  {
    cabinetNumber: 8,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '경수현',
    unavailableReason: '',
  },
  {
    cabinetNumber: 9,
    status: 'unrent',
    start: '',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    cabinetNumber: 10,
    status: 'unrent',
    start: '',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    cabinetNumber: 11,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '오지현',
    unavailableReason: '',
  },
  {
    cabinetNumber: 12,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '이윤서',
    unavailableReason: '',
  },
  {
    cabinetNumber: 13,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '송현지',
    unavailableReason: '',
  },
  {
    cabinetNumber: 14,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '구나영',
    unavailableReason: '',
  },
  {
    cabinetNumber: 15,
    status: 'unrent',
    start: '',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    cabinetNumber: 16,
    status: 'rent',
    start: '2023.03.29',
    end: '2023.07.10',
    lender: '최세호',
    unavailableReason: '',
  },
];
