export const umbrellaStatus = [
  {
    umbrellaNumber: 1,
    status: 'rent',
    end: '2023.05.22',
    lender: '이지우',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 2,
    status: 'rent',
    end: '2023.05.22',
    lender: '경수현',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 3,
    status: 'unavailable',
    end: '',
    lender: '',
    unavailableReason: 'stolen',
  },
  {
    umbrellaNumber: 4,
    status: 'unrent',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 5,
    status: 'rent',
    end: '2023.05.22',
    lender: '김진호',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 6,
    status: 'rent',
    end: '2023.05.22',
    lender: '신민서',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 7,
    status: 'unavailable',
    end: '',
    lender: '',
    unavailableReason: 'loss',
  },
  {
    umbrellaNumber: 8,
    status: 'unrent',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 9,
    status: 'rent',
    end: '2023.05.22',
    lender: '안성민',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 10,
    status: 'rent',
    end: '2023.05.22',
    lender: '이승훈',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 11,
    status: 'unrent',
    end: '',
    lender: '',
    unavailableReason: '',
  },
  {
    umbrellaNumber: 12,
    status: 'rent',
    end: '2023.05.22',
    lender: '최서영',
    unavailableReason: '',
  },
];
